services:

  web:
    image: ghcr.io/ram2005024/baadfaad:latest
    container_name: django_web
    command:
      - uv
      - run
      - gunicorn
      - config.wsgi:application
      - --bind
      - 0.0.0.0:8000
      - --workers
      - "3"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery:
    image: ghcr.io/ram2005024/baadfaad:latest
    container_name: django_celery
    command:
      - uv
      - run
      - celery
      - -A
      - config
      - worker
      - --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: django_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: django_redis
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
