# Generated by Django 6.1.1 on 2026-09-24 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DB_CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
